using System.Collections;
using FishNet.Object;
using FishNet.Object.Synchronizing;
using UnityEngine;

public class PoseableLimbIKController : NetworkBehaviour
{
    [Header("Player Bindings")]
    [SerializeField]
    private PoseableLimbBinding[] bindings =
        new PoseableLimbBinding[4];

    [Header("Ragdoll Reaction")]
    [SerializeField]
    private TemporaryRagdollController ragdollController;

    [SerializeField, Min(0f)]
    private float resetDelay = 3f;

    [Header("Target Space")]
    [Tooltip(
        "The four limb targets should be direct children of this transform."
    )]
    [SerializeField]
    private Transform targetSpace;

    [Header("Hand Targets")]
    [SerializeField]
    private Transform leftHandTarget;

    [SerializeField]
    private Transform rightHandTarget;

    [Header("Foot Targets")]
    [SerializeField]
    private Transform leftFootTarget;

    [SerializeField]
    private Transform rightFootTarget;

    [Header("Target Movement")]
    [SerializeField, Min(0f)]
    private float handMoveSpeed = 1.5f;

    [SerializeField, Min(0f)]
    private float footMoveSpeed = 1f;

    [SerializeField, Min(0f)]
    private float visualSmoothing = 15f;

    [Header("Left Hand Bounds")]
    [SerializeField]
    private Vector2 leftHandMinimum =
        new(-1.2f, 0.7f);

    [SerializeField]
    private Vector2 leftHandMaximum =
        new(-0.05f, 2.1f);

    [Header("Right Hand Bounds")]
    [SerializeField]
    private Vector2 rightHandMinimum =
        new(0.05f, 0.7f);

    [SerializeField]
    private Vector2 rightHandMaximum =
        new(1.2f, 2.1f);

    [Header("Left Foot Bounds")]
    [SerializeField]
    private Vector2 leftFootMinimum =
        new(-0.8f, 0f);

    [SerializeField]
    private Vector2 leftFootMaximum =
        new(-0.05f, 1f);

    [Header("Right Foot Bounds")]
    [SerializeField]
    private Vector2 rightFootMinimum =
        new(0.05f, 0f);

    [SerializeField]
    private Vector2 rightFootMaximum =
        new(0.8f, 1f);

    [Header("Foot Support")]
    [Tooltip(
        "How far above its starting floor height a foot may be " +
        "while still counting as planted."
    )]
    [SerializeField, Min(0f)]
    private float plantedHeightTolerance = 0.08f;

    [Tooltip(
        "Both feet must be unsupported for this long before falling."
    )]
    [SerializeField, Min(0f)]
    private float unsupportedGraceTime = 0.25f;

    [Header("Procedural Torso Targets")]
    [Tooltip(
        "Additive rotation target for the first spine bone. " +
        "Use an Override Transform constraint in Pivot space."
    )]
    [SerializeField]
    private Transform spinePoseTarget;

    [Tooltip(
        "Additive rotation target for the chest bone. " +
        "Use an Override Transform constraint in Pivot space."
    )]
    [SerializeField]
    private Transform chestPoseTarget;

    [Tooltip(
        "Additive counter-rotation target for the neck or head bone. " +
        "Use an Override Transform constraint in Pivot space."
    )]
    [SerializeField]
    private Transform headPoseTarget;

    [Header("Balance Input")]
    [Tooltip(
        "Height above the starting foot height that counts as a full leg lift."
    )]
    [SerializeField, Min(0.01f)]
    private float fullLegLiftHeight = 0.45f;

    [Tooltip(
        "Horizontal support-point movement that counts as full balance influence."
    )]
    [SerializeField, Min(0.01f)]
    private float fullSupportPointShift = 0.35f;

    [Tooltip(
        "Average horizontal hand movement that counts as full arm influence."
    )]
    [SerializeField, Min(0.01f)]
    private float fullArmHorizontalReach = 0.75f;

    [Tooltip(
        "Average vertical hand movement that counts as full arm influence."
    )]
    [SerializeField, Min(0.01f)]
    private float fullArmVerticalReach = 0.75f;

    [Range(0f, 1f)]
    [SerializeField]
    private float supportPointInfluence = 0.7f;

    [Range(0f, 1f)]
    [SerializeField]
    private float raisedLegInfluence = 0.3f;

    [Header("Torso Pose")]
    [Tooltip(
        "Maximum side bend generated by the feet and support point."
    )]
    [SerializeField, Min(0f)]
    private float maximumBalanceSideLean = 8f;

    [Tooltip(
        "Maximum additional side bend generated by the average hand position."
    )]
    [SerializeField, Min(0f)]
    private float maximumArmSideLean = 3f;

    [Tooltip(
        "Maximum chest pitch generated by raising or lowering both hands."
    )]
    [SerializeField, Min(0f)]
    private float maximumArmPitch = 3f;

    [Tooltip(
        "Use -1 if support-based side leaning is reversed for this model."
    )]
    [SerializeField]
    private float balanceLeanDirection = 1f;

    [Tooltip(
        "Use -1 for arm counter-balancing, or 1 to lean toward the hands."
    )]
    [SerializeField]
    private float armLeanDirection = -1f;

    [Tooltip(
        "Use -1 if arm-driven forward/backward pitch is reversed."
    )]
    [SerializeField]
    private float armPitchDirection = 1f;

    [Range(0f, 1f)]
    [SerializeField]
    private float spineLeanShare = 0.4f;

    [Range(0f, 1f)]
    [SerializeField]
    private float chestLeanShare = 0.6f;

    [Range(0f, 1.5f)]
    [SerializeField]
    private float headSideCounterbalance = 0.8f;

    [Range(0f, 1.5f)]
    [SerializeField]
    private float headPitchCounterbalance = 0.6f;

    [Tooltip(
        "Local axis used for left/right body bending. " +
        "For a character standing in the XY plane this is usually Z."
    )]
    [SerializeField]
    private Vector3 sideLeanLocalAxis = Vector3.forward;

    [Tooltip(
        "Local axis used for forward/backward chest pitch. " +
        "This is usually X."
    )]
    [SerializeField]
    private Vector3 pitchLocalAxis = Vector3.right;

    [SerializeField, Min(0f)]
    private float bodyPoseVisualSmoothing = 10f;

    /*
     * Limb positions are authoritative on the server and are stored
     * in targetSpace-local coordinates.
     */
    private readonly SyncVar<Vector3> _leftHandPosition = new();
    private readonly SyncVar<Vector3> _rightHandPosition = new();
    private readonly SyncVar<Vector3> _leftFootPosition = new();
    private readonly SyncVar<Vector3> _rightFootPosition = new();

    /*
     * These are rotations of additive pose-source transforms.
     * They do not directly replace bone rotations.
     */
    private readonly SyncVar<Quaternion> _spinePoseRotation = new();
    private readonly SyncVar<Quaternion> _chestPoseRotation = new();
    private readonly SyncVar<Quaternion> _headPoseRotation = new();

    private readonly SyncVar<bool> _isFallen = new(false);
    private readonly SyncVar<bool> _stateInitialized = new(false);

    private Coroutine _fallRoutine;

    private float _leftHandDepth;
    private float _rightHandDepth;
    private float _leftFootDepth;
    private float _rightFootDepth;

    private float _leftFootFloorHeight;
    private float _rightFootFloorHeight;
    private float _startingSupportPointX;
    private float _unsupportedTimer;

    private Vector3 _startingLeftHandPosition;
    private Vector3 _startingRightHandPosition;
    private Vector3 _startingLeftFootPosition;
    private Vector3 _startingRightFootPosition;

    private Quaternion _startingSpinePoseRotation;
    private Quaternion _startingChestPoseRotation;
    private Quaternion _startingHeadPoseRotation;

    private bool _startingPoseStored;

    public bool IsFallen => _isFallen.Value;

    private void Awake()
    {
        CaptureStartingPoseIfPossible();
    }

    public override void OnStartServer()
    {
        base.OnStartServer();

        InitializeAuthoritativeState();

        TimeManager.OnTick += HandleServerTick;
    }

    public override void OnStopServer()
    {
        TimeManager.OnTick -= HandleServerTick;

        if (_fallRoutine != null)
        {
            StopCoroutine(_fallRoutine);
            _fallRoutine = null;
        }

        base.OnStopServer();
    }

    private void Update()
    {
        if (!_stateInitialized.Value)
            return;

        ApplyReplicatedTargetPositions();
        ApplyReplicatedTorsoPose();
    }

    private void CaptureStartingPoseIfPossible()
    {
        if (_startingPoseStored)
            return;

        if (targetSpace == null ||
            leftHandTarget == null ||
            rightHandTarget == null ||
            leftFootTarget == null ||
            rightFootTarget == null ||
            spinePoseTarget == null ||
            chestPoseTarget == null ||
            headPoseTarget == null)
        {
            return;
        }

        _startingLeftHandPosition =
            GetTargetSpacePosition(leftHandTarget);

        _startingRightHandPosition =
            GetTargetSpacePosition(rightHandTarget);

        _startingLeftFootPosition =
            GetTargetSpacePosition(leftFootTarget);

        _startingRightFootPosition =
            GetTargetSpacePosition(rightFootTarget);

        _startingSpinePoseRotation =
            spinePoseTarget.localRotation;

        _startingChestPoseRotation =
            chestPoseTarget.localRotation;

        _startingHeadPoseRotation =
            headPoseTarget.localRotation;

        _startingSupportPointX =
            (_startingLeftFootPosition.x +
             _startingRightFootPosition.x) * 0.5f;

        _startingPoseStored = true;
    }

    [Server]
    private void InitializeAuthoritativeState()
    {
        if (!ValidateRequiredReferences())
            return;

        CaptureStartingPoseIfPossible();

        if (!_startingPoseStored)
            return;

        _leftHandPosition.Value =
            _startingLeftHandPosition;

        _rightHandPosition.Value =
            _startingRightHandPosition;

        _leftFootPosition.Value =
            _startingLeftFootPosition;

        _rightFootPosition.Value =
            _startingRightFootPosition;

        _leftHandDepth =
            _startingLeftHandPosition.z;

        _rightHandDepth =
            _startingRightHandPosition.z;

        _leftFootDepth =
            _startingLeftFootPosition.z;

        _rightFootDepth =
            _startingRightFootPosition.z;

        _leftFootFloorHeight =
            _startingLeftFootPosition.y;

        _rightFootFloorHeight =
            _startingRightFootPosition.y;

        _spinePoseRotation.Value =
            _startingSpinePoseRotation;

        _chestPoseRotation.Value =
            _startingChestPoseRotation;

        _headPoseRotation.Value =
            _startingHeadPoseRotation;

        _unsupportedTimer = 0f;
        _isFallen.Value = false;
        _stateInitialized.Value = true;
    }

    private void HandleServerTick()
    {
        if (!_stateInitialized.Value ||
            _isFallen.Value)
        {
            return;
        }

        if (!ValidateRequiredReferences())
            return;

        ReadPlayerInputs(
            out Vector2 leftArmInput,
            out Vector2 rightArmInput,
            out Vector2 leftLegInput,
            out Vector2 rightLegInput
        );

        float deltaTime =
            (float)TimeManager.TickDelta;

        _leftHandPosition.Value = MoveTargetInPlane(
            _leftHandPosition.Value,
            leftArmInput,
            leftHandMinimum,
            leftHandMaximum,
            _leftHandDepth,
            handMoveSpeed,
            deltaTime
        );

        _rightHandPosition.Value = MoveTargetInPlane(
            _rightHandPosition.Value,
            rightArmInput,
            rightHandMinimum,
            rightHandMaximum,
            _rightHandDepth,
            handMoveSpeed,
            deltaTime
        );

        _leftFootPosition.Value = MoveTargetInPlane(
            _leftFootPosition.Value,
            leftLegInput,
            leftFootMinimum,
            leftFootMaximum,
            _leftFootDepth,
            footMoveSpeed,
            deltaTime
        );

        _rightFootPosition.Value = MoveTargetInPlane(
            _rightFootPosition.Value,
            rightLegInput,
            rightFootMinimum,
            rightFootMaximum,
            _rightFootDepth,
            footMoveSpeed,
            deltaTime
        );

        UpdateAuthoritativeTorsoPose();
        UpdateSupportState(deltaTime);
    }

    private void ReadPlayerInputs(
        out Vector2 leftArmInput,
        out Vector2 rightArmInput,
        out Vector2 leftLegInput,
        out Vector2 rightLegInput)
    {
        leftArmInput = Vector2.zero;
        rightArmInput = Vector2.zero;
        leftLegInput = Vector2.zero;
        rightLegInput = Vector2.zero;

        foreach (PlayerControlChannel channel
                 in PlayerControlChannel.ServerChannels)
        {
            if (channel == null)
                continue;

            PoseableLimbAction assignedAction =
                GetActionForSlot(channel.Slot);

            Vector2 input =
                channel.RawServerAxisInput;

            switch (assignedAction)
            {
                case PoseableLimbAction.LeftArm:
                    leftArmInput = input;
                    break;

                case PoseableLimbAction.RightArm:
                    rightArmInput = input;
                    break;

                case PoseableLimbAction.LeftLeg:
                    leftLegInput = input;
                    break;

                case PoseableLimbAction.RightLeg:
                    rightLegInput = input;
                    break;
            }
        }
    }

    private PoseableLimbAction GetActionForSlot(
        PlayerSlot slot)
    {
        if (bindings == null)
            return PoseableLimbAction.None;

        foreach (PoseableLimbBinding binding in bindings)
        {
            if (binding.PlayerSlot == slot)
                return binding.Action;
        }

        return PoseableLimbAction.None;
    }

    private static Vector3 MoveTargetInPlane(
        Vector3 currentPosition,
        Vector2 input,
        Vector2 minimum,
        Vector2 maximum,
        float fixedDepth,
        float moveSpeed,
        float deltaTime)
    {
        input =
            Vector2.ClampMagnitude(input, 1f);

        currentPosition.x +=
            input.x *
            moveSpeed *
            deltaTime;

        currentPosition.y +=
            input.y *
            moveSpeed *
            deltaTime;

        currentPosition.x =
            Mathf.Clamp(
                currentPosition.x,
                minimum.x,
                maximum.x
            );

        currentPosition.y =
            Mathf.Clamp(
                currentPosition.y,
                minimum.y,
                maximum.y
            );

        currentPosition.z =
            fixedDepth;

        return currentPosition;
    }

    /*
     * Server-authoritative torso solver.
     *
     * It generates additive rotations only for the spine, chest,
     * and head pose-source transforms. It never rotates the pelvis,
     * body root, or leg hierarchy.
     */
    [Server]
    private void UpdateAuthoritativeTorsoPose()
    {
        float supportPointInfluenceValue =
            CalculateSupportPointInfluence();

        float raisedLegInfluenceValue =
            CalculateRaisedLegBalance();

        float combinedBalance =
            supportPointInfluenceValue *
            supportPointInfluence +
            raisedLegInfluenceValue *
            raisedLegInfluence;

        combinedBalance =
            Mathf.Clamp(
                combinedBalance,
                -1f,
                1f
            );

        float armHorizontal =
            CalculateArmHorizontalInfluence();

        float armVertical =
            CalculateArmVerticalInfluence();

        float balanceSideLean =
            combinedBalance *
            maximumBalanceSideLean *
            balanceLeanDirection;

        float armSideLean =
            armHorizontal *
            maximumArmSideLean *
            armLeanDirection;

        float totalSideLean =
            balanceSideLean +
            armSideLean;

        float chestPitch =
            -armVertical *
            maximumArmPitch *
            armPitchDirection;

        float spineSideLean =
            totalSideLean *
            spineLeanShare;

        float chestSideLean =
            totalSideLean *
            chestLeanShare;

        float headSideLean =
            -totalSideLean *
            headSideCounterbalance;

        float headPitch =
            -chestPitch *
            headPitchCounterbalance;

        _spinePoseRotation.Value =
            BuildPoseTargetRotation(
                _startingSpinePoseRotation,
                spineSideLean,
                0f
            );

        _chestPoseRotation.Value =
            BuildPoseTargetRotation(
                _startingChestPoseRotation,
                chestSideLean,
                chestPitch
            );

        _headPoseRotation.Value =
            BuildPoseTargetRotation(
                _startingHeadPoseRotation,
                headSideLean,
                headPitch
            );
    }

    private float CalculateLegLiftAmount(
        Vector3 footPosition,
        float floorHeight)
    {
        float heightAboveFloor =
            footPosition.y -
            floorHeight;

        return Mathf.Clamp01(
            heightAboveFloor /
            fullLegLiftHeight
        );
    }

    private float CalculateRaisedLegBalance()
    {
        float leftLift =
            CalculateLegLiftAmount(
                _leftFootPosition.Value,
                _leftFootFloorHeight
            );

        float rightLift =
            CalculateLegLiftAmount(
                _rightFootPosition.Value,
                _rightFootFloorHeight
            );

        /*
         * Positive:
         * left leg is raised more, so support is primarily right.
         *
         * Negative:
         * right leg is raised more, so support is primarily left.
         */
        return leftLift -
               rightLift;
    }

    private float CalculateSupportPointInfluence()
    {
        float leftLift =
            CalculateLegLiftAmount(
                _leftFootPosition.Value,
                _leftFootFloorHeight
            );

        float rightLift =
            CalculateLegLiftAmount(
                _rightFootPosition.Value,
                _rightFootFloorHeight
            );

        float leftSupportWeight =
            1f -
            leftLift;

        float rightSupportWeight =
            1f -
            rightLift;

        float totalSupportWeight =
            leftSupportWeight +
            rightSupportWeight;

        /*
         * When both feet are fully raised, the fall system takes over.
         * Returning zero prevents an arbitrary torso snap during the
         * unsupported grace period.
         */
        if (totalSupportWeight <= 0.001f)
            return 0f;

        float currentSupportPointX =
            (
                _leftFootPosition.Value.x *
                leftSupportWeight +
                _rightFootPosition.Value.x *
                rightSupportWeight
            ) /
            totalSupportWeight;

        float supportOffsetX =
            currentSupportPointX -
            _startingSupportPointX;

        return Mathf.Clamp(
            supportOffsetX /
            fullSupportPointShift,
            -1f,
            1f
        );
    }

    private float CalculateArmHorizontalInfluence()
    {
        float leftOffset =
            _leftHandPosition.Value.x -
            _startingLeftHandPosition.x;

        float rightOffset =
            _rightHandPosition.Value.x -
            _startingRightHandPosition.x;

        float averageOffset =
            (leftOffset +
             rightOffset) * 0.5f;

        return Mathf.Clamp(
            averageOffset /
            fullArmHorizontalReach,
            -1f,
            1f
        );
    }

    private float CalculateArmVerticalInfluence()
    {
        float leftOffset =
            _leftHandPosition.Value.y -
            _startingLeftHandPosition.y;

        float rightOffset =
            _rightHandPosition.Value.y -
            _startingRightHandPosition.y;

        float averageOffset =
            (leftOffset +
             rightOffset) * 0.5f;

        return Mathf.Clamp(
            averageOffset /
            fullArmVerticalReach,
            -1f,
            1f
        );
    }

    private Quaternion BuildPoseTargetRotation(
        Quaternion startingRotation,
        float sideLeanDegrees,
        float pitchDegrees)
    {
        Vector3 safeSideAxis =
            GetSafeAxis(
                sideLeanLocalAxis,
                Vector3.forward
            );

        Vector3 safePitchAxis =
            GetSafeAxis(
                pitchLocalAxis,
                Vector3.right
            );

        Quaternion sideRotation =
            Quaternion.AngleAxis(
                sideLeanDegrees,
                safeSideAxis
            );

        Quaternion pitchRotation =
            Quaternion.AngleAxis(
                pitchDegrees,
                safePitchAxis
            );

        return startingRotation *
               sideRotation *
               pitchRotation;
    }

    private static Vector3 GetSafeAxis(
        Vector3 configuredAxis,
        Vector3 fallbackAxis)
    {
        if (configuredAxis.sqrMagnitude <=
            0.000001f)
        {
            return fallbackAxis;
        }

        return configuredAxis.normalized;
    }

    private void UpdateSupportState(float deltaTime)
    {
        bool leftFootSupported =
            IsFootSupported(
                _leftFootPosition.Value,
                _leftFootFloorHeight
            );

        bool rightFootSupported =
            IsFootSupported(
                _rightFootPosition.Value,
                _rightFootFloorHeight
            );

        bool bothFeetUnsupported =
            !leftFootSupported &&
            !rightFootSupported;

        if (!bothFeetUnsupported)
        {
            _unsupportedTimer = 0f;
            return;
        }

        _unsupportedTimer +=
            deltaTime;

        if (_unsupportedTimer >=
            unsupportedGraceTime)
        {
            TriggerFall();
        }
    }

    private bool IsFootSupported(
        Vector3 footPosition,
        float floorHeight)
    {
        float maximumSupportedHeight =
            floorHeight +
            plantedHeightTolerance;

        return footPosition.y <=
               maximumSupportedHeight;
    }

    [Server]
    private void TriggerFall()
    {
        if (_isFallen.Value)
            return;

        _isFallen.Value = true;
        _unsupportedTimer = 0f;

        TriggerFallObserversRpc();

        if (_fallRoutine != null)
            StopCoroutine(_fallRoutine);

        _fallRoutine =
            StartCoroutine(
                ServerResetAfterDelay()
            );

        Debug.Log(
            "Both feet lost support. Starting ragdoll.",
            this
        );
    }

    private IEnumerator ServerResetAfterDelay()
    {
        yield return new WaitForSeconds(
            resetDelay
        );

        _fallRoutine = null;

        ResetServerState();
        ResetBodyObserversRpc();
    }

    [ServerRpc(RequireOwnership = false)]
    public void RequestResetServerRpc()
    {
        ResetBody();
    }

    [Server]
    public void ResetBody()
    {
        if (_fallRoutine != null)
        {
            StopCoroutine(_fallRoutine);
            _fallRoutine = null;
        }

        ResetServerState();
        ResetBodyObserversRpc();
    }

    [Server]
    private void ResetServerState()
    {
        InitializeAuthoritativeState();
    }

    [ObserversRpc]
    private void TriggerFallObserversRpc()
    {
        if (ragdollController != null)
            ragdollController.BeginRagdoll();
    }

    [ObserversRpc]
    private void ResetBodyObserversRpc()
    {
        SnapVisualTargetsToStartingPose();

        if (ragdollController != null)
            ragdollController.ResetRagdoll();
    }

    private void ApplyReplicatedTargetPositions()
    {
        float interpolationAmount =
            CalculateExponentialInterpolation(
                visualSmoothing,
                Time.deltaTime
            );

        ApplyTargetPosition(
            leftHandTarget,
            _leftHandPosition.Value,
            interpolationAmount
        );

        ApplyTargetPosition(
            rightHandTarget,
            _rightHandPosition.Value,
            interpolationAmount
        );

        ApplyTargetPosition(
            leftFootTarget,
            _leftFootPosition.Value,
            interpolationAmount
        );

        ApplyTargetPosition(
            rightFootTarget,
            _rightFootPosition.Value,
            interpolationAmount
        );
    }

    private void ApplyReplicatedTorsoPose()
    {
        float interpolationAmount =
            CalculateExponentialInterpolation(
                bodyPoseVisualSmoothing,
                Time.deltaTime
            );

        ApplyTargetRotation(
            spinePoseTarget,
            _spinePoseRotation.Value,
            interpolationAmount
        );

        ApplyTargetRotation(
            chestPoseTarget,
            _chestPoseRotation.Value,
            interpolationAmount
        );

        ApplyTargetRotation(
            headPoseTarget,
            _headPoseRotation.Value,
            interpolationAmount
        );
    }

    private void SnapVisualTargetsToStartingPose()
    {
        CaptureStartingPoseIfPossible();

        if (!_startingPoseStored)
            return;

        leftHandTarget.localPosition =
            _startingLeftHandPosition;

        rightHandTarget.localPosition =
            _startingRightHandPosition;

        leftFootTarget.localPosition =
            _startingLeftFootPosition;

        rightFootTarget.localPosition =
            _startingRightFootPosition;

        spinePoseTarget.localRotation =
            _startingSpinePoseRotation;

        chestPoseTarget.localRotation =
            _startingChestPoseRotation;

        headPoseTarget.localRotation =
            _startingHeadPoseRotation;
    }

    private static float CalculateExponentialInterpolation(
        float smoothing,
        float deltaTime)
    {
        return 1f -
               Mathf.Exp(
                   -smoothing *
                   deltaTime
               );
    }

    private static void ApplyTargetPosition(
        Transform target,
        Vector3 targetLocalPosition,
        float interpolationAmount)
    {
        if (target == null)
            return;

        target.localPosition =
            Vector3.Lerp(
                target.localPosition,
                targetLocalPosition,
                interpolationAmount
            );
    }

    private static void ApplyTargetRotation(
        Transform target,
        Quaternion targetLocalRotation,
        float interpolationAmount)
    {
        if (target == null)
            return;

        target.localRotation =
            Quaternion.Slerp(
                target.localRotation,
                targetLocalRotation,
                interpolationAmount
            );
    }

    private Vector3 GetTargetSpacePosition(
        Transform target)
    {
        return targetSpace.InverseTransformPoint(
            target.position
        );
    }

    private bool ValidateRequiredReferences()
    {
        if (targetSpace == null)
        {
            Debug.LogError(
                "Poseable body has no Target Space assigned.",
                this
            );

            return false;
        }

        if (leftHandTarget == null ||
            rightHandTarget == null ||
            leftFootTarget == null ||
            rightFootTarget == null)
        {
            Debug.LogError(
                "One or more poseable-body IK targets are missing.",
                this
            );

            return false;
        }

        if (spinePoseTarget == null ||
            chestPoseTarget == null ||
            headPoseTarget == null)
        {
            Debug.LogError(
                "One or more procedural torso pose targets are missing.",
                this
            );

            return false;
        }

        return true;
    }

#if UNITY_EDITOR

    private void OnValidate()
    {
        ValidateBindings();

        if (sideLeanLocalAxis.sqrMagnitude <=
            0.000001f)
        {
            sideLeanLocalAxis =
                Vector3.forward;
        }

        if (pitchLocalAxis.sqrMagnitude <=
            0.000001f)
        {
            pitchLocalAxis =
                Vector3.right;
        }
    }

    private void ValidateBindings()
    {
        if (bindings == null)
            return;

        for (int i = 0;
             i < bindings.Length;
             i++)
        {
            PoseableLimbBinding current =
                bindings[i];

            if (current.PlayerSlot ==
                PlayerSlot.None)
            {
                continue;
            }

            for (int j = i + 1;
                 j < bindings.Length;
                 j++)
            {
                PoseableLimbBinding other =
                    bindings[j];

                if (current.PlayerSlot ==
                    other.PlayerSlot)
                {
                    Debug.LogWarning(
                        $"{current.PlayerSlot} is assigned " +
                        "more than once.",
                        this
                    );
                }

                if (current.Action !=
                        PoseableLimbAction.None &&
                    current.Action ==
                        other.Action)
                {
                    Debug.LogWarning(
                        $"{current.Action} is assigned " +
                        "to more than one player.",
                        this
                    );
                }
            }
        }
    }

    private void OnDrawGizmosSelected()
    {
        if (targetSpace == null)
            return;

        Matrix4x4 previousMatrix =
            Gizmos.matrix;

        Gizmos.matrix =
            targetSpace.localToWorldMatrix;

        DrawControlArea(
            leftHandMinimum,
            leftHandMaximum,
            GetEditorDepth(leftHandTarget)
        );

        DrawControlArea(
            rightHandMinimum,
            rightHandMaximum,
            GetEditorDepth(rightHandTarget)
        );

        DrawControlArea(
            leftFootMinimum,
            leftFootMaximum,
            GetEditorDepth(leftFootTarget)
        );

        DrawControlArea(
            rightFootMinimum,
            rightFootMaximum,
            GetEditorDepth(rightFootTarget)
        );

        Gizmos.matrix =
            previousMatrix;
    }

    private float GetEditorDepth(
        Transform target)
    {
        if (target == null ||
            targetSpace == null)
        {
            return 0f;
        }

        return targetSpace
            .InverseTransformPoint(
                target.position
            )
            .z;
    }

    private static void DrawControlArea(
        Vector2 minimum,
        Vector2 maximum,
        float depth)
    {
        Vector3 center = new(
            (minimum.x + maximum.x) * 0.5f,
            (minimum.y + maximum.y) * 0.5f,
            depth
        );

        Vector3 size = new(
            maximum.x - minimum.x,
            maximum.y - minimum.y,
            0.01f
        );

        Gizmos.DrawWireCube(
            center,
            size
        );
    }

#endif
}
